# Compile ce dossier sans GitHub. Les utilisateurs n'ont besoin que de m5-dial.yaml.

substitutions:
  device_name: m5stack-dial
  device_friendly_name: M5Stack Dial
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_encryption_key: !secret api_encryption_key
  ota_password: !secret ota_password
  ap_ssid: Dial Fallback Hotspot
  ap_password: "changeme-dial-ap"

  timezone: Europe/Paris
  weather_entity: weather.disabled
  aqi_entity: sensor.disabled
  climate_entity: climate.disabled
  music_player_entity: media_player.disabled
  timer_entity: timer.disabled

dial_lights: []

packages:
  firmware: !include dial.yaml
